#!/usr/bin/env python3
"""Build the Realidea v16 Portable_AI script section from reusable sources.

The output is one dependency-free Ruby file in load order:
model -> move effects -> decision core -> Realidea adapter/hook.

Usage:
    python3 build_portable_ai.py
    python3 build_portable_ai.py --out generated/Portable_AI.rb
"""

import argparse
import shutil
import subprocess
from pathlib import Path


STUDY = Path(__file__).resolve().parents[1]
CORE_SOURCES = [
    STUDY / "portable_ai" / "model.rb",
    STUDY / "portable_ai" / "effects.rb",
    STUDY / "portable_ai" / "core.rb",
]
TARGETS = {
    "realidea": {
        "sources": CORE_SOURCES + [
            STUDY / "adapters" / "realidea" / "Portable_AI_Adapter.rb",
            STUDY / "adapters" / "realidea" / "Portable_AI_Gauntlet.rb",
        ],
        "out": STUDY / "generated" / "Portable_AI.rb",
    },
    "reborn": {
        "sources": CORE_SOURCES + [
            STUDY / "adapters" / "reborn" / "Portable_AI_Adapter.rb",
            # Roster data must precede the gauntlet, which resolves team sets from it.
            # Regenerate with tools/make_gauntlet_teams.py.
            STUDY / "generated" / "gauntlet_teams_reborn.rb",
            # Tier suite; merges into the archetype suite's SETS, so it must follow it.
            # Regenerate with tools/make_tier_teams.py.
            STUDY / "generated" / "tier_teams_reborn.rb",
            STUDY / "adapters" / "reborn" / "Portable_AI_Gauntlet.rb",
        ],
        "out": STUDY / "generated" / "Portable_AI_Reborn.rb",
    },
}
# Tokens that must never appear in the engine-free core. 0.5.0 adds the three
# constant namespaces its new tables could most easily have leaked: an ability or item
# table written with PBAbilities::GUTS instead of the string "GUTS" would compile in
# Reborn and fail to load in Realidea, which is exactly the portability the split
# exists to protect.
FORBIDDEN_CORE_TOKENS = (
    "PokeBattle_",
    "PBMoves",
    "PBEffects",
    "PBTrainerAI",
    "PBAbilities",
    "PBItems",
    "PBFields",
    "@battle",
)


def validate_core():
    failures = []
    for path in CORE_SOURCES:
        text = path.read_text(encoding="utf-8")
        code = "\n".join(
            line for line in text.splitlines()
            if not line.lstrip().startswith("#")
        )
        for token in FORBIDDEN_CORE_TOKENS:
            if token in code:
                failures.append(f"{path.relative_to(STUDY)} contains {token!r}")
    if failures:
        raise SystemExit("engine-free core check failed:\n  " + "\n  ".join(failures))


def build(out_path, sources):
    chunks = [
        "# Portable_AI — generated by tools/build_portable_ai.py; do not hand-edit.\n",
        "# Source modules remain separately reviewable under _AI-Study/.\n\n",
    ]
    for path in sources:
        relative = path.relative_to(STUDY).as_posix()
        chunks.append(f"# ===== BEGIN {relative} =====\n")
        chunks.append(path.read_text(encoding="utf-8").rstrip() + "\n")
        chunks.append(f"# ===== END {relative} =====\n\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(chunks), encoding="utf-8", newline="\n")


def ruby_syntax_check(out_path):
    ruby = shutil.which("ruby")
    if not ruby:
        print("ruby not found; skipped syntax check")
        return
    subprocess.run([ruby, "-c", str(out_path)], check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=sorted(TARGETS), default="realidea")
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--no-ruby-check", action="store_true")
    args = parser.parse_args()

    target = TARGETS[args.target]
    out_path = args.out or target["out"]
    validate_core()
    build(out_path, target["sources"])
    if not args.no_ruby_check:
        ruby_syntax_check(out_path)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
