#!/usr/bin/env python3
"""Compile validated team JSONs into the Team_Overrides Ruby section
(TEAM-DESIGN.md §6.5 deployment). Output is Ruby 1.8-compatible (Realidea is
RGSS1) and fails safe: any lookup/build error falls back to the original party.

Override key = [trainer_type_id, trainer_name, original ace level] — the ace
level disambiguates recurring fights that share class+name. Collisions between
distinct battles that share all three are reported and deduped (first wins;
identical key implies an identical-looking fight anyway).

Usage: emit_registry.py out.rb teams_boss.json teams_filler.json [...]
"""
import json, sys, re

def rsym(s):
    assert re.fullmatch(r'[A-Za-z0-9_]+', s), f"unsafe symbol: {s!r}"
    return ":" + s

def rstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def emit_mon(m):
    iv = m.get("iv", 31)
    ivs = [iv] * 6 if isinstance(iv, int) else iv
    moves = "[" + ",".join(rsym(x) for x in m["moves"]) + "]"
    item = rsym(m["item"]) if m.get("item") else "nil"
    return (f'[{rstr(m["species"])},{m["level"]},{moves},{item},'
            f'{m.get("ability", 0)},{rsym(m["nature"])},'
            f'{ivs},{m.get("ev", [0]*6)}]')

def main(out_path, *team_files):
    teams = []
    for f in team_files:
        teams += json.load(open(f))
    lines = [
        "# Team_Overrides — generated by _AI-Study/tools/emit_registry.py; do not hand-edit.",
        "# See _AI-Study/TEAM-DESIGN.md §6.5. Keyed [trainer_type_id, name, orig ace level];",
        "# unknown keys fall through to the original party, so this section is inert for",
        "# every battle it doesn't know about.",
        "",
        "TEAM_OVERRIDES = {}",
        "TEAM_OVERRIDE_ITEMS = {}",
        "",
    ]
    seen = {}
    collisions = 0
    for t in teams:
        key = (t["type_id"], t["name"], t["orig_ace_level"])
        if key in seen:
            collisions += 1
            print(f"collision: {t['id']} shares key {key} with {seen[key]} — skipped")
            continue
        seen[key] = t["id"]
        rkey = f'[{t["type_id"]},{rstr(t["name"])},{t["orig_ace_level"]}]'
        lines.append(f'# {t["id"]}')
        lines.append(f'TEAM_OVERRIDES[{rkey}] = [')
        for m in t["mons"]:
            lines.append(f'  {emit_mon(m)},')
        lines.append(']')
        titems = t.get("trainer_items", [])
        if titems:
            lines.append(f'TEAM_OVERRIDE_ITEMS[{rkey}] = '
                         f'[{",".join(rsym(x) for x in titems)}]')
        lines.append("")
    lines += [
        "alias team_override_orig_createTrainer createTrainer",
        "def createTrainer(trainerid, trainername, party, items=[])",
        "  begin",
        "    ace = nil",
        "    for p in party",
        "      ace = p.level if ace.nil? || p.level > ace",
        "    end",
        "    key = [trainerid, trainername, ace]",
        "    spec = TEAM_OVERRIDES[key]",
        "    if spec",
        "      newparty = []",
        "      for ms in spec",
        "        poke = createPokemon(ms[0], ms[1], ms[2].dup)",
        "        if poke",
        "          poke.setItem(getConst(PBItems, ms[3])) if ms[3]",
        "          poke.setAbility(ms[4])",
        "          poke.iv = ms[6].dup",
        "          poke.ev = ms[7].dup",
        "          poke.setNature(ms[5])   # calls calcStats — keep last",
        "          newparty.push(poke)",
        "        end",
        "      end",
        "      if newparty.length == spec.length",
        "        party = newparty",
        "        ti = TEAM_OVERRIDE_ITEMS[key]",
        "        if ti && items.length == 0",
        "          items = ti.collect { |s| getConst(PBItems, s) }",
        "        end",
        "      end",
        "    end",
        "  rescue",
        "    # any failure -> keep the original party untouched",
        "  end",
        "  return team_override_orig_createTrainer(trainerid, trainername, party, items)",
        "end",
    ]
    open(out_path, "w").write("\n".join(lines) + "\n")
    print(f"{len(seen)} overrides emitted to {out_path} ({collisions} collisions skipped)")
    import shutil, subprocess
    if shutil.which("ruby"):
        subprocess.run(["ruby", "-c", out_path], check=True)
    else:
        print("WARNING: ruby not found — emitted file is NOT syntax-checked")

if __name__ == "__main__":
    main(sys.argv[1], *sys.argv[2:])
