#!/usr/bin/env python3
"""Compile validated team JSONs into the Team_Overrides Ruby section
(TEAM-DESIGN.md §6.5 deployment). Output is Ruby 1.8-compatible (Realidea is
RGSS1) and fails safe: any lookup/build error falls back to the original party.

Override key = [map_id, trainer_type_id, trainer_name, original ace level].

Class+name alone repeats all over the game, and the ace level does not reliably
separate the repeats: Alba's two early fights both ace at 60 because she carries a
Braviary pinned there, so keyed on ace they are one fight and one of the two teams
is silently dropped. Where the battle HAPPENS is the part that is actually unique
to it, so the map leads the key.

The ace slot is nil for a fight built on `balanceo`: the engine derives every level
from the player's own party, so that battle presents a different ace on every
playthrough and has no fixed number to key on.

What is left over are twin trainers standing on the same map under the same class
and name at the same level — the game hands createTrainer nothing that tells them
apart except their original party, which this key does not look at. They are
reported and deduped (first wins), so both twins field the first one's team.

Usage: emit_registry.py out.rb teams_boss.json teams_filler.json [...]
"""
import json, sys, re

def rsym(s):
    assert re.fullmatch(r'[A-Za-z0-9_]+', s), f"unsafe symbol: {s!r}"
    return ":" + s

def rstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def emit_level(lv):
    """A level is a number, or ["balanceo", offset] for a fight that scales to the
    player. `balanceo` is the game's own method (Entrenadores.rb); the builder calls
    it at battle time so the swapped team tracks the player as the original did."""
    if isinstance(lv, int):
        return str(lv)
    token, off = lv
    return f'[{rstr(token)},{off}]'

def emit_mon(m):
    iv = m.get("iv", 31)
    ivs = [iv] * 6 if isinstance(iv, int) else iv
    moves = "[" + ",".join(rsym(x) for x in m["moves"]) + "]"
    item = rsym(m["item"]) if m.get("item") else "nil"
    return (f'[{rstr(m["species"])},{emit_level(m["level"])},{moves},{item},'
            f'{m.get("ability", 0)},{rsym(m["nature"])},'
            f'{ivs},{m.get("ev", [0]*6)}]')

def main(out_path, *team_files):
    teams = []
    for f in team_files:
        with open(f, encoding="utf-8") as team_file:
            teams += json.load(team_file)
    # two paths: inline createTrainer teams (have orig_ace_level) and dat
    # pbLoadTrainer teams (have orig_species_ids). See TEAM-DESIGN.md §6.5.
    inline = [t for t in teams if "orig_ace_level" in t]
    datt = [t for t in teams if "orig_species_ids" in t]
    lines = [
        "# Team_Overrides — generated by _AI-Study/tools/emit_registry.py; do not hand-edit.",
        "# See _AI-Study/TEAM-DESIGN.md §6.5. Two registries, two battle paths:",
        "#   TEAM_OVERRIDES     — inline createTrainer fights,",
        "#                        key [map_id, type_id, name, ace level or nil]",
        "#   TEAM_OVERRIDES_DAT — pbTrainerBattle/dat fights, key [type_id, partyid, [species ids]]",
        "# Unknown keys fall through to the original party; this section is inert otherwise.",
        "",
        "TEAM_OVERRIDES = {}",
        "TEAM_OVERRIDE_ITEMS = {}",
        "TEAM_OVERRIDES_DAT = {}",
        'TEAM_OVERRIDES_DISABLE_FILE = "Data/original_teams.txt"',
        "",
    ]
    seen = {}
    collisions = 0
    for t in inline:
        # nil ace: this fight's levels are the player's, see the module docstring
        ace = t["orig_ace_level"] if isinstance(t["orig_ace_level"], int) else None
        key = (t["map"], t["type_id"], t["name"], ace)
        rkey = (f'[{t["map"]},{t["type_id"]},{rstr(t["name"])},'
                f'{ace if ace is not None else "nil"}]')
        if key in seen:
            collisions += 1
            print(f"collision: {t['id']} shares key {key} with {seen[key]} — skipped")
            continue
        seen[key] = t["id"]
        lines.append(f'# {t["id"]}')
        lines.append(f'TEAM_OVERRIDES[{rkey}] = [')
        for m in t["mons"]:
            lines.append(f'  {emit_mon(m)},')
        lines.append(']')
        titems = t.get("trainer_items", [])
        if titems:
            lines.append(f'TEAM_OVERRIDE_ITEMS[{rkey}] = '
                         f'[{",".join(rsym(x) for x in titems)}]')
        lines.append("")
    seen_dat = {}
    for t in datt:
        key = (t["type_id"], t["partyid"], t["orig_ace_level"], tuple(t["orig_species_ids"]))
        if key in seen_dat:
            collisions += 1
            print(f"collision(dat): {t['id']} shares key {key} with {seen_dat[key]} — skipped")
            continue
        seen_dat[key] = t["id"]
        rkey = f'[{t["type_id"]},{t["partyid"]},{t["orig_ace_level"]},{list(t["orig_species_ids"])}]'
        lines.append(f'# {t["id"]}  (orig: {"/".join(t.get("orig_species", []))})')
        lines.append(f'TEAM_OVERRIDES_DAT[{rkey}] = [')
        for m in t["mons"]:
            lines.append(f'  {emit_mon(m)},')
        lines.append(']')
        lines.append("")
    lines += [
        "# Shared builder: spec row = [species, level, [moves], item, abil, nature, ivs, evs]",
        "#",
        "# A lowercase species is a METHOD name, not a species: the rival fights build",
        "# their starter slot from Pokes Rivales (owenpoke2, albapoke1, ...), which pick",
        "# a fakemon from $game_variables[54] so the rival carries the starter matching",
        "# yours. Real internal names are uppercase, so the case test is unambiguous.",
        "def team_override_build(spec)",
        "  newparty = []",
        "  for ms in spec",
        "    sp = ms[0]",
        "    sp = send(sp) if sp.is_a?(String) && sp[0,1] == sp[0,1].downcase",
        "    # a scaled level, [\"balanceo\", offset]: the original event wrote the level",
        "    # as balanceo+1 / balanceo-2 so the fight tracks the player's party. Call",
        "    # the same method here and the swapped team scales exactly as it did.",
        "    lv = ms[1]",
        "    lv = send(lv[0]) + lv[1] if lv.is_a?(Array)",
        "    # an empty move list means 'let the engine pick' -- the starter slot has",
        "    # no fixed species here, so it cannot carry a precomputed set",
        "    poke = ms[2].empty? ? createPokemon(sp, lv) : createPokemon(sp, lv, ms[2].dup)",
        "    if poke",
        "      poke.setItem(getConst(PBItems, ms[3])) if ms[3]",
        "      poke.setAbility(ms[4])",
        "      poke.iv = ms[6].dup",
        "      poke.ev = ms[7].dup",
        "      poke.setNature(ms[5])   # calls calcStats — keep last",
        "      newparty.push(poke)",
        "    end",
        "  end",
        "  newparty",
        "end",
        "",
        "# Put Data/original_teams.txt beside the game data to keep the original",
        "# trainer rosters while leaving the installed AI and other patches active.",
        "def team_overrides_enabled?",
        "  return !File.exist?(TEAM_OVERRIDES_DISABLE_FILE)",
        "rescue",
        "  return true",
        "end",
        "",
        "# Path 1: inline createTrainer fights.",
        "alias team_override_orig_createTrainer createTrainer",
        "def createTrainer(trainerid, trainername, party, items=[])",
        "  if !team_overrides_enabled?",
        "    return team_override_orig_createTrainer(trainerid, trainername, party, items)",
        "  end",
        "  begin",
        "    ace = nil",
        "    for p in party",
        "      next if p.nil?   # original events sometimes have typo'd species -> nil mons",
        "      ace = p.level if ace.nil? || p.level > ace",
        "    end",
        "    mapid = $game_map ? $game_map.map_id : 0",
        "    key = [mapid, trainerid, trainername, ace]",
        "    spec = TEAM_OVERRIDES[key]",
        "    if !spec",
        "      # a `balanceo` fight is stored with nil in the ace slot: every level in",
        "      # it comes from the player's party, so there is no fixed ace to match",
        "      key = [mapid, trainerid, trainername, nil]",
        "      spec = TEAM_OVERRIDES[key]",
        "    end",
        "    if spec",
        "      newparty = team_override_build(spec)",
        "      if newparty.length == spec.length",
        "        party = newparty",
        "        ti = TEAM_OVERRIDE_ITEMS[key]",
        "        if ti && items.length == 0",
        "          items = ti.collect { |s| getConst(PBItems, s) }",
        "        end",
        "      end",
        "    end",
        "  rescue",
        "    # any failure -> keep the original party untouched",
        "  end",
        "  return team_override_orig_createTrainer(trainerid, trainername, party, items)",
        "end",
        "",
        "# Path 2: dat fights via pbTrainerBattle -> pbLoadTrainer. Let the original",
        "# build the party, then swap it by original species-id signature (encoding-proof).",
        "alias team_override_orig_pbLoadTrainer pbLoadTrainer",
        "def pbLoadTrainer(trainerid, trainername, partyid=0)",
        "  result = team_override_orig_pbLoadTrainer(trainerid, trainername, partyid)",
        "  return result if !team_overrides_enabled?",
        "  begin",
        "    if result && result[0] && result[0].party",
        "      tid = trainerid.is_a?(Integer) ? trainerid : getID(PBTrainers, trainerid)",
        "      ace = 0",
        "      for p in result[0].party",
        "        ace = p.level if !p.nil? && p.level > ace",
        "      end",
        "      sig = result[0].party.reject { |p| p.nil? }.collect { |p| p.species }.sort",
        "      key = [tid, partyid, ace, sig]",
        "      spec = TEAM_OVERRIDES_DAT[key]",
        "      if spec",
        "        newparty = team_override_build(spec)",
        "        result[0].party = newparty if newparty.length == spec.length",
        "      end",
        "    end",
        "  rescue",
        "  end",
        "  return result",
        "end",
    ]
    with open(out_path, "w", encoding="utf-8", newline="\n") as out_file:
        out_file.write("\n".join(lines) + "\n")
    print(f"{len(seen)} inline + {len(seen_dat)} dat overrides emitted ({collisions} collisions skipped)")
    import shutil, subprocess
    if shutil.which("ruby"):
        subprocess.run(["ruby", "-c", out_path], check=True)
    else:
        print("WARNING: ruby not found — emitted file is NOT syntax-checked")

if __name__ == "__main__":
    main(sys.argv[1], *sys.argv[2:])
