#!/usr/bin/env python3
"""Compile validated team JSONs into the Team_Overrides Ruby section
(TEAM-DESIGN.md §6.5 deployment). Output is Ruby 1.8-compatible (Realidea is
RGSS1) and fails safe: any lookup/build error falls back to the original party.

Override key = [trainer_type_id, trainer_name, original ace level] — the ace
level disambiguates recurring fights that share class+name. Collisions between
distinct battles that share all three are reported and deduped (first wins;
identical key implies an identical-looking fight anyway).

Usage: emit_registry.py out.rb teams_boss.json teams_filler.json [...]
"""
import json, sys, re

def rsym(s):
    assert re.fullmatch(r'[A-Za-z0-9_]+', s), f"unsafe symbol: {s!r}"
    return ":" + s

def rstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def emit_mon(m):
    iv = m.get("iv", 31)
    ivs = [iv] * 6 if isinstance(iv, int) else iv
    moves = "[" + ",".join(rsym(x) for x in m["moves"]) + "]"
    item = rsym(m["item"]) if m.get("item") else "nil"
    return (f'[{rstr(m["species"])},{m["level"]},{moves},{item},'
            f'{m.get("ability", 0)},{rsym(m["nature"])},'
            f'{ivs},{m.get("ev", [0]*6)}]')

def main(out_path, *team_files):
    teams = []
    for f in team_files:
        teams += json.load(open(f))
    # two paths: inline createTrainer teams (have orig_ace_level) and dat
    # pbLoadTrainer teams (have orig_species_ids). See TEAM-DESIGN.md §6.5.
    inline = [t for t in teams if "orig_ace_level" in t]
    datt = [t for t in teams if "orig_species_ids" in t]
    lines = [
        "# Team_Overrides — generated by _AI-Study/tools/emit_registry.py; do not hand-edit.",
        "# See _AI-Study/TEAM-DESIGN.md §6.5. Two registries, two battle paths:",
        "#   TEAM_OVERRIDES     — inline createTrainer fights, key [type_id, name, ace level]",
        "#   TEAM_OVERRIDES_DAT — pbTrainerBattle/dat fights, key [type_id, partyid, [species ids]]",
        "# Unknown keys fall through to the original party; this section is inert otherwise.",
        "",
        "TEAM_OVERRIDES = {}",
        "TEAM_OVERRIDE_ITEMS = {}",
        "TEAM_OVERRIDES_DAT = {}",
        "",
    ]
    seen = {}
    collisions = 0
    for t in inline:
        key = (t["type_id"], t["name"], t["orig_ace_level"])
        if key in seen:
            collisions += 1
            print(f"collision: {t['id']} shares key {key} with {seen[key]} — skipped")
            continue
        seen[key] = t["id"]
        rkey = f'[{t["type_id"]},{rstr(t["name"])},{t["orig_ace_level"]}]'
        lines.append(f'# {t["id"]}')
        lines.append(f'TEAM_OVERRIDES[{rkey}] = [')
        for m in t["mons"]:
            lines.append(f'  {emit_mon(m)},')
        lines.append(']')
        titems = t.get("trainer_items", [])
        if titems:
            lines.append(f'TEAM_OVERRIDE_ITEMS[{rkey}] = '
                         f'[{",".join(rsym(x) for x in titems)}]')
        lines.append("")
    seen_dat = {}
    for t in datt:
        key = (t["type_id"], t["partyid"], t["orig_ace_level"], tuple(t["orig_species_ids"]))
        if key in seen_dat:
            collisions += 1
            print(f"collision(dat): {t['id']} shares key {key} with {seen_dat[key]} — skipped")
            continue
        seen_dat[key] = t["id"]
        rkey = f'[{t["type_id"]},{t["partyid"]},{t["orig_ace_level"]},{list(t["orig_species_ids"])}]'
        lines.append(f'# {t["id"]}  (orig: {"/".join(t.get("orig_species", []))})')
        lines.append(f'TEAM_OVERRIDES_DAT[{rkey}] = [')
        for m in t["mons"]:
            lines.append(f'  {emit_mon(m)},')
        lines.append(']')
        lines.append("")
    lines += [
        "begin",
        "  File.open('Data/team_override_log.txt', 'wb') { |fh|",
        "    fh.write(\"loaded #{TEAM_OVERRIDES.size} inline + #{TEAM_OVERRIDES_DAT.size} dat overrides at boot\\n\") }",
        "rescue; end",
        "",
        "# Shared builder: spec row = [species, level, [moves], item, abil, nature, ivs, evs]",
        "def team_override_build(spec)",
        "  newparty = []",
        "  for ms in spec",
        "    poke = createPokemon(ms[0], ms[1], ms[2].dup)",
        "    if poke",
        "      poke.setItem(getConst(PBItems, ms[3])) if ms[3]",
        "      poke.setAbility(ms[4])",
        "      poke.iv = ms[6].dup",
        "      poke.ev = ms[7].dup",
        "      poke.setNature(ms[5])   # calls calcStats — keep last",
        "      newparty.push(poke)",
        "    end",
        "  end",
        "  newparty",
        "end",
        "",
        "# Path 1: inline createTrainer fights.",
        "alias team_override_orig_createTrainer createTrainer",
        "def createTrainer(trainerid, trainername, party, items=[])",
        "  begin",
        "    ace = nil",
        "    for p in party",
        "      ace = p.level if ace.nil? || p.level > ace",
        "    end",
        "    key = [trainerid, trainername, ace]",
        "    spec = TEAM_OVERRIDES[key]",
        "    begin",
        "      File.open('Data/team_override_log.txt', 'ab') { |fh|",
        "        fh.write(\"createTrainer #{key.inspect} -> #{spec ? 'HIT' : 'miss'}\\n\") }",
        "    rescue; end",
        "    if spec",
        "      newparty = team_override_build(spec)",
        "      if newparty.length == spec.length",
        "        party = newparty",
        "        ti = TEAM_OVERRIDE_ITEMS[key]",
        "        if ti && items.length == 0",
        "          items = ti.collect { |s| getConst(PBItems, s) }",
        "        end",
        "      end",
        "    end",
        "  rescue",
        "    # any failure -> keep the original party untouched",
        "  end",
        "  return team_override_orig_createTrainer(trainerid, trainername, party, items)",
        "end",
        "",
        "# Path 2: dat fights via pbTrainerBattle -> pbLoadTrainer. Let the original",
        "# build the party, then swap it by original species-id signature (encoding-proof).",
        "alias team_override_orig_pbLoadTrainer pbLoadTrainer",
        "def pbLoadTrainer(trainerid, trainername, partyid=0)",
        "  result = team_override_orig_pbLoadTrainer(trainerid, trainername, partyid)",
        "  begin",
        "    if result && result[0] && result[0].party",
        "      tid = trainerid.is_a?(Integer) ? trainerid : getID(PBTrainers, trainerid)",
        "      ace = 0",
        "      for p in result[0].party",
        "        ace = p.level if p.level > ace",
        "      end",
        "      sig = result[0].party.collect { |p| p.species }.sort",
        "      key = [tid, partyid, ace, sig]",
        "      spec = TEAM_OVERRIDES_DAT[key]",
        "      begin",
        "        File.open('Data/team_override_log.txt', 'ab') { |fh|",
        "          fh.write(\"pbLoadTrainer #{key.inspect} -> #{spec ? 'HIT' : 'miss'}\\n\") }",
        "      rescue; end",
        "      if spec",
        "        newparty = team_override_build(spec)",
        "        result[0].party = newparty if newparty.length == spec.length",
        "      end",
        "    end",
        "  rescue",
        "  end",
        "  return result",
        "end",
    ]
    open(out_path, "w").write("\n".join(lines) + "\n")
    print(f"{len(seen)} inline + {len(seen_dat)} dat overrides emitted ({collisions} collisions skipped)")
    import shutil, subprocess
    if shutil.which("ruby"):
        subprocess.run(["ruby", "-c", out_path], check=True)
    else:
        print("WARNING: ruby not found — emitted file is NOT syntax-checked")

if __name__ == "__main__":
    main(sys.argv[1], *sys.argv[2:])
